# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_quantum_tic_tac_toe.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(917, 888)
        self.actionNumber_of_rounds = QAction(MainWindow)
        self.actionNumber_of_rounds.setObjectName(u"actionNumber_of_rounds")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gameFrame = QFrame(self.centralwidget)
        self.gameFrame.setObjectName(u"gameFrame")
        self.gameFrame.setGeometry(QRect(160, 190, 600, 604))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFrame.sizePolicy().hasHeightForWidth())
        self.gameFrame.setSizePolicy(sizePolicy)
        self.gameFrame.setFrameShape(QFrame.NoFrame)
        self.gameFrame.setFrameShadow(QFrame.Raised)
        self.vLine_2 = QFrame(self.gameFrame)
        self.vLine_2.setObjectName(u"vLine_2")
        self.vLine_2.setGeometry(QRect(400, 0, 2, 604))
        sizePolicy.setHeightForWidth(self.vLine_2.sizePolicy().hasHeightForWidth())
        self.vLine_2.setSizePolicy(sizePolicy)
        self.vLine_2.setFrameShadow(QFrame.Plain)
        self.vLine_2.setLineWidth(2)
        self.vLine_2.setFrameShape(QFrame.VLine)
        self.frame_9 = QFrame(self.gameFrame)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(402, 404, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QFrame.NoFrame)
        self.frame_9.setFrameShadow(QFrame.Sunken)
        self.frame_9.setLineWidth(1)
        self.label9_8 = QLabel(self.frame_9)
        self.label9_8.setObjectName(u"label9_8")
        self.label9_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label9_8.sizePolicy().hasHeightForWidth())
        self.label9_8.setSizePolicy(sizePolicy1)
        self.label9_8.setScaledContents(True)
        self.label9_4 = QLabel(self.frame_9)
        self.label9_4.setObjectName(u"label9_4")
        self.label9_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_4.sizePolicy().hasHeightForWidth())
        self.label9_4.setSizePolicy(sizePolicy1)
        self.label9_4.setScaledContents(True)
        self.label9_1 = QLabel(self.frame_9)
        self.label9_1.setObjectName(u"label9_1")
        self.label9_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_1.sizePolicy().hasHeightForWidth())
        self.label9_1.setSizePolicy(sizePolicy1)
        self.label9_1.setScaledContents(True)
        self.label9_7 = QLabel(self.frame_9)
        self.label9_7.setObjectName(u"label9_7")
        self.label9_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_7.sizePolicy().hasHeightForWidth())
        self.label9_7.setSizePolicy(sizePolicy1)
        self.label9_7.setScaledContents(True)
        self.label9_3 = QLabel(self.frame_9)
        self.label9_3.setObjectName(u"label9_3")
        self.label9_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_3.sizePolicy().hasHeightForWidth())
        self.label9_3.setSizePolicy(sizePolicy1)
        self.label9_3.setScaledContents(True)
        self.big_label9 = QLabel(self.frame_9)
        self.big_label9.setObjectName(u"big_label9")
        self.big_label9.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label9.sizePolicy().hasHeightForWidth())
        self.big_label9.setSizePolicy(sizePolicy)
        self.big_label9.setScaledContents(True)
        self.label9_9 = QLabel(self.frame_9)
        self.label9_9.setObjectName(u"label9_9")
        self.label9_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_9.sizePolicy().hasHeightForWidth())
        self.label9_9.setSizePolicy(sizePolicy1)
        self.label9_9.setScaledContents(True)
        self.label9_6 = QLabel(self.frame_9)
        self.label9_6.setObjectName(u"label9_6")
        self.label9_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_6.sizePolicy().hasHeightForWidth())
        self.label9_6.setSizePolicy(sizePolicy1)
        self.label9_6.setScaledContents(True)
        self.label9_5 = QLabel(self.frame_9)
        self.label9_5.setObjectName(u"label9_5")
        self.label9_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_5.sizePolicy().hasHeightForWidth())
        self.label9_5.setSizePolicy(sizePolicy1)
        self.label9_5.setScaledContents(True)
        self.label9_2 = QLabel(self.frame_9)
        self.label9_2.setObjectName(u"label9_2")
        self.label9_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label9_2.sizePolicy().hasHeightForWidth())
        self.label9_2.setSizePolicy(sizePolicy1)
        self.label9_2.setScaledContents(True)
        self.button9 = QPushButton(self.frame_9)
        self.button9.setObjectName(u"button9")
        self.button9.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        self.button9.setFlat(True)
        self.hLine_2 = QFrame(self.gameFrame)
        self.hLine_2.setObjectName(u"hLine_2")
        self.hLine_2.setGeometry(QRect(-2, 402, 604, 2))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.hLine_2.sizePolicy().hasHeightForWidth())
        self.hLine_2.setSizePolicy(sizePolicy2)
        self.hLine_2.setFrameShadow(QFrame.Plain)
        self.hLine_2.setLineWidth(2)
        self.hLine_2.setFrameShape(QFrame.HLine)
        self.frame_7 = QFrame(self.gameFrame)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(-2, 404, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QFrame.NoFrame)
        self.frame_7.setFrameShadow(QFrame.Sunken)
        self.frame_7.setLineWidth(1)
        self.label7_8 = QLabel(self.frame_7)
        self.label7_8.setObjectName(u"label7_8")
        self.label7_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_8.sizePolicy().hasHeightForWidth())
        self.label7_8.setSizePolicy(sizePolicy1)
        self.label7_8.setScaledContents(True)
        self.label7_4 = QLabel(self.frame_7)
        self.label7_4.setObjectName(u"label7_4")
        self.label7_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_4.sizePolicy().hasHeightForWidth())
        self.label7_4.setSizePolicy(sizePolicy1)
        self.label7_4.setScaledContents(True)
        self.label7_1 = QLabel(self.frame_7)
        self.label7_1.setObjectName(u"label7_1")
        self.label7_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_1.sizePolicy().hasHeightForWidth())
        self.label7_1.setSizePolicy(sizePolicy1)
        self.label7_1.setScaledContents(True)
        self.label7_7 = QLabel(self.frame_7)
        self.label7_7.setObjectName(u"label7_7")
        self.label7_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_7.sizePolicy().hasHeightForWidth())
        self.label7_7.setSizePolicy(sizePolicy1)
        self.label7_7.setScaledContents(True)
        self.label7_3 = QLabel(self.frame_7)
        self.label7_3.setObjectName(u"label7_3")
        self.label7_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_3.sizePolicy().hasHeightForWidth())
        self.label7_3.setSizePolicy(sizePolicy1)
        self.label7_3.setScaledContents(True)
        self.big_label7 = QLabel(self.frame_7)
        self.big_label7.setObjectName(u"big_label7")
        self.big_label7.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label7.sizePolicy().hasHeightForWidth())
        self.big_label7.setSizePolicy(sizePolicy)
        self.big_label7.setScaledContents(True)
        self.label7_9 = QLabel(self.frame_7)
        self.label7_9.setObjectName(u"label7_9")
        self.label7_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_9.sizePolicy().hasHeightForWidth())
        self.label7_9.setSizePolicy(sizePolicy1)
        self.label7_9.setScaledContents(True)
        self.label7_6 = QLabel(self.frame_7)
        self.label7_6.setObjectName(u"label7_6")
        self.label7_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_6.sizePolicy().hasHeightForWidth())
        self.label7_6.setSizePolicy(sizePolicy1)
        self.label7_6.setScaledContents(True)
        self.label7_5 = QLabel(self.frame_7)
        self.label7_5.setObjectName(u"label7_5")
        self.label7_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_5.sizePolicy().hasHeightForWidth())
        self.label7_5.setSizePolicy(sizePolicy1)
        self.label7_5.setScaledContents(True)
        self.label7_2 = QLabel(self.frame_7)
        self.label7_2.setObjectName(u"label7_2")
        self.label7_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label7_2.sizePolicy().hasHeightForWidth())
        self.label7_2.setSizePolicy(sizePolicy1)
        self.label7_2.setScaledContents(True)
        self.button7 = QPushButton(self.frame_7)
        self.button7.setObjectName(u"button7")
        self.button7.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setFlat(True)
        self.frame_5 = QFrame(self.gameFrame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(200, 202, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Sunken)
        self.frame_5.setLineWidth(1)
        self.label5_8 = QLabel(self.frame_5)
        self.label5_8.setObjectName(u"label5_8")
        self.label5_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_8.sizePolicy().hasHeightForWidth())
        self.label5_8.setSizePolicy(sizePolicy1)
        self.label5_8.setScaledContents(True)
        self.label5_4 = QLabel(self.frame_5)
        self.label5_4.setObjectName(u"label5_4")
        self.label5_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_4.sizePolicy().hasHeightForWidth())
        self.label5_4.setSizePolicy(sizePolicy1)
        self.label5_4.setScaledContents(True)
        self.label5_1 = QLabel(self.frame_5)
        self.label5_1.setObjectName(u"label5_1")
        self.label5_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_1.sizePolicy().hasHeightForWidth())
        self.label5_1.setSizePolicy(sizePolicy1)
        self.label5_1.setScaledContents(True)
        self.label5_7 = QLabel(self.frame_5)
        self.label5_7.setObjectName(u"label5_7")
        self.label5_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_7.sizePolicy().hasHeightForWidth())
        self.label5_7.setSizePolicy(sizePolicy1)
        self.label5_7.setScaledContents(True)
        self.label5_3 = QLabel(self.frame_5)
        self.label5_3.setObjectName(u"label5_3")
        self.label5_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_3.sizePolicy().hasHeightForWidth())
        self.label5_3.setSizePolicy(sizePolicy1)
        self.label5_3.setScaledContents(True)
        self.big_label5 = QLabel(self.frame_5)
        self.big_label5.setObjectName(u"big_label5")
        self.big_label5.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label5.sizePolicy().hasHeightForWidth())
        self.big_label5.setSizePolicy(sizePolicy)
        self.big_label5.setScaledContents(True)
        self.label5_9 = QLabel(self.frame_5)
        self.label5_9.setObjectName(u"label5_9")
        self.label5_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_9.sizePolicy().hasHeightForWidth())
        self.label5_9.setSizePolicy(sizePolicy1)
        self.label5_9.setScaledContents(True)
        self.label5_6 = QLabel(self.frame_5)
        self.label5_6.setObjectName(u"label5_6")
        self.label5_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_6.sizePolicy().hasHeightForWidth())
        self.label5_6.setSizePolicy(sizePolicy1)
        self.label5_6.setScaledContents(True)
        self.label5_5 = QLabel(self.frame_5)
        self.label5_5.setObjectName(u"label5_5")
        self.label5_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_5.sizePolicy().hasHeightForWidth())
        self.label5_5.setSizePolicy(sizePolicy1)
        self.label5_5.setScaledContents(True)
        self.label5_2 = QLabel(self.frame_5)
        self.label5_2.setObjectName(u"label5_2")
        self.label5_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label5_2.sizePolicy().hasHeightForWidth())
        self.label5_2.setSizePolicy(sizePolicy1)
        self.label5_2.setScaledContents(True)
        self.button5 = QPushButton(self.frame_5)
        self.button5.setObjectName(u"button5")
        self.button5.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        self.button5.setFlat(True)
        self.frame_6 = QFrame(self.gameFrame)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(402, 202, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Sunken)
        self.frame_6.setLineWidth(1)
        self.label6_8 = QLabel(self.frame_6)
        self.label6_8.setObjectName(u"label6_8")
        self.label6_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_8.sizePolicy().hasHeightForWidth())
        self.label6_8.setSizePolicy(sizePolicy1)
        self.label6_8.setScaledContents(True)
        self.label6_4 = QLabel(self.frame_6)
        self.label6_4.setObjectName(u"label6_4")
        self.label6_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_4.sizePolicy().hasHeightForWidth())
        self.label6_4.setSizePolicy(sizePolicy1)
        self.label6_4.setScaledContents(True)
        self.label6_1 = QLabel(self.frame_6)
        self.label6_1.setObjectName(u"label6_1")
        self.label6_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_1.sizePolicy().hasHeightForWidth())
        self.label6_1.setSizePolicy(sizePolicy1)
        self.label6_1.setScaledContents(True)
        self.label6_7 = QLabel(self.frame_6)
        self.label6_7.setObjectName(u"label6_7")
        self.label6_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_7.sizePolicy().hasHeightForWidth())
        self.label6_7.setSizePolicy(sizePolicy1)
        self.label6_7.setScaledContents(True)
        self.label6_3 = QLabel(self.frame_6)
        self.label6_3.setObjectName(u"label6_3")
        self.label6_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_3.sizePolicy().hasHeightForWidth())
        self.label6_3.setSizePolicy(sizePolicy1)
        self.label6_3.setScaledContents(True)
        self.big_label6 = QLabel(self.frame_6)
        self.big_label6.setObjectName(u"big_label6")
        self.big_label6.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label6.sizePolicy().hasHeightForWidth())
        self.big_label6.setSizePolicy(sizePolicy)
        self.big_label6.setScaledContents(True)
        self.label6_9 = QLabel(self.frame_6)
        self.label6_9.setObjectName(u"label6_9")
        self.label6_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_9.sizePolicy().hasHeightForWidth())
        self.label6_9.setSizePolicy(sizePolicy1)
        self.label6_9.setScaledContents(True)
        self.label6_6 = QLabel(self.frame_6)
        self.label6_6.setObjectName(u"label6_6")
        self.label6_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_6.sizePolicy().hasHeightForWidth())
        self.label6_6.setSizePolicy(sizePolicy1)
        self.label6_6.setScaledContents(True)
        self.label6_5 = QLabel(self.frame_6)
        self.label6_5.setObjectName(u"label6_5")
        self.label6_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_5.sizePolicy().hasHeightForWidth())
        self.label6_5.setSizePolicy(sizePolicy1)
        self.label6_5.setScaledContents(True)
        self.label6_2 = QLabel(self.frame_6)
        self.label6_2.setObjectName(u"label6_2")
        self.label6_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label6_2.sizePolicy().hasHeightForWidth())
        self.label6_2.setSizePolicy(sizePolicy1)
        self.label6_2.setScaledContents(True)
        self.button6 = QPushButton(self.frame_6)
        self.button6.setObjectName(u"button6")
        self.button6.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        self.button6.setFlat(True)
        self.frame_8 = QFrame(self.gameFrame)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(200, 404, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QFrame.NoFrame)
        self.frame_8.setFrameShadow(QFrame.Sunken)
        self.frame_8.setLineWidth(1)
        self.label8_8 = QLabel(self.frame_8)
        self.label8_8.setObjectName(u"label8_8")
        self.label8_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_8.sizePolicy().hasHeightForWidth())
        self.label8_8.setSizePolicy(sizePolicy1)
        self.label8_8.setScaledContents(True)
        self.label8_4 = QLabel(self.frame_8)
        self.label8_4.setObjectName(u"label8_4")
        self.label8_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_4.sizePolicy().hasHeightForWidth())
        self.label8_4.setSizePolicy(sizePolicy1)
        self.label8_4.setScaledContents(True)
        self.label8_1 = QLabel(self.frame_8)
        self.label8_1.setObjectName(u"label8_1")
        self.label8_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_1.sizePolicy().hasHeightForWidth())
        self.label8_1.setSizePolicy(sizePolicy1)
        self.label8_1.setScaledContents(True)
        self.label8_7 = QLabel(self.frame_8)
        self.label8_7.setObjectName(u"label8_7")
        self.label8_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_7.sizePolicy().hasHeightForWidth())
        self.label8_7.setSizePolicy(sizePolicy1)
        self.label8_7.setScaledContents(True)
        self.label8_3 = QLabel(self.frame_8)
        self.label8_3.setObjectName(u"label8_3")
        self.label8_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_3.sizePolicy().hasHeightForWidth())
        self.label8_3.setSizePolicy(sizePolicy1)
        self.label8_3.setScaledContents(True)
        self.big_label8 = QLabel(self.frame_8)
        self.big_label8.setObjectName(u"big_label8")
        self.big_label8.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label8.sizePolicy().hasHeightForWidth())
        self.big_label8.setSizePolicy(sizePolicy)
        self.big_label8.setScaledContents(True)
        self.label8_9 = QLabel(self.frame_8)
        self.label8_9.setObjectName(u"label8_9")
        self.label8_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_9.sizePolicy().hasHeightForWidth())
        self.label8_9.setSizePolicy(sizePolicy1)
        self.label8_9.setScaledContents(True)
        self.label8_6 = QLabel(self.frame_8)
        self.label8_6.setObjectName(u"label8_6")
        self.label8_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_6.sizePolicy().hasHeightForWidth())
        self.label8_6.setSizePolicy(sizePolicy1)
        self.label8_6.setScaledContents(True)
        self.label8_5 = QLabel(self.frame_8)
        self.label8_5.setObjectName(u"label8_5")
        self.label8_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_5.sizePolicy().hasHeightForWidth())
        self.label8_5.setSizePolicy(sizePolicy1)
        self.label8_5.setScaledContents(True)
        self.label8_2 = QLabel(self.frame_8)
        self.label8_2.setObjectName(u"label8_2")
        self.label8_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label8_2.sizePolicy().hasHeightForWidth())
        self.label8_2.setSizePolicy(sizePolicy1)
        self.label8_2.setScaledContents(True)
        self.button8 = QPushButton(self.frame_8)
        self.button8.setObjectName(u"button8")
        self.button8.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setFlat(True)
        self.hLine_1 = QFrame(self.gameFrame)
        self.hLine_1.setObjectName(u"hLine_1")
        self.hLine_1.setGeometry(QRect(-2, 200, 604, 2))
        sizePolicy2.setHeightForWidth(self.hLine_1.sizePolicy().hasHeightForWidth())
        self.hLine_1.setSizePolicy(sizePolicy2)
        self.hLine_1.setFrameShadow(QFrame.Plain)
        self.hLine_1.setLineWidth(2)
        self.hLine_1.setFrameShape(QFrame.HLine)
        self.frame_1 = QFrame(self.gameFrame)
        self.frame_1.setObjectName(u"frame_1")
        self.frame_1.setGeometry(QRect(-2, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setFrameShape(QFrame.NoFrame)
        self.frame_1.setFrameShadow(QFrame.Sunken)
        self.frame_1.setLineWidth(1)
        self.label1_8 = QLabel(self.frame_1)
        self.label1_8.setObjectName(u"label1_8")
        self.label1_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_8.sizePolicy().hasHeightForWidth())
        self.label1_8.setSizePolicy(sizePolicy1)
        self.label1_8.setScaledContents(True)
        self.label1_4 = QLabel(self.frame_1)
        self.label1_4.setObjectName(u"label1_4")
        self.label1_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_4.sizePolicy().hasHeightForWidth())
        self.label1_4.setSizePolicy(sizePolicy1)
        self.label1_4.setScaledContents(True)
        self.label1_1 = QLabel(self.frame_1)
        self.label1_1.setObjectName(u"label1_1")
        self.label1_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_1.sizePolicy().hasHeightForWidth())
        self.label1_1.setSizePolicy(sizePolicy1)
        self.label1_1.setScaledContents(True)
        self.label1_7 = QLabel(self.frame_1)
        self.label1_7.setObjectName(u"label1_7")
        self.label1_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_7.sizePolicy().hasHeightForWidth())
        self.label1_7.setSizePolicy(sizePolicy1)
        self.label1_7.setScaledContents(True)
        self.label1_3 = QLabel(self.frame_1)
        self.label1_3.setObjectName(u"label1_3")
        self.label1_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_3.sizePolicy().hasHeightForWidth())
        self.label1_3.setSizePolicy(sizePolicy1)
        self.label1_3.setScaledContents(True)
        self.big_label1 = QLabel(self.frame_1)
        self.big_label1.setObjectName(u"big_label1")
        self.big_label1.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label1.sizePolicy().hasHeightForWidth())
        self.big_label1.setSizePolicy(sizePolicy)
        self.big_label1.setScaledContents(True)
        self.label1_9 = QLabel(self.frame_1)
        self.label1_9.setObjectName(u"label1_9")
        self.label1_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_9.sizePolicy().hasHeightForWidth())
        self.label1_9.setSizePolicy(sizePolicy1)
        self.label1_9.setScaledContents(True)
        self.label1_6 = QLabel(self.frame_1)
        self.label1_6.setObjectName(u"label1_6")
        self.label1_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_6.sizePolicy().hasHeightForWidth())
        self.label1_6.setSizePolicy(sizePolicy1)
        self.label1_6.setScaledContents(True)
        self.label1_5 = QLabel(self.frame_1)
        self.label1_5.setObjectName(u"label1_5")
        self.label1_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_5.sizePolicy().hasHeightForWidth())
        self.label1_5.setSizePolicy(sizePolicy1)
        self.label1_5.setScaledContents(True)
        self.label1_2 = QLabel(self.frame_1)
        self.label1_2.setObjectName(u"label1_2")
        self.label1_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy1)
        self.label1_2.setScaledContents(True)
        self.button1 = QPushButton(self.frame_1)
        self.button1.setObjectName(u"button1")
        self.button1.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setFlat(True)
        self.frame_4 = QFrame(self.gameFrame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(-2, 202, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Sunken)
        self.frame_4.setLineWidth(1)
        self.label4_8 = QLabel(self.frame_4)
        self.label4_8.setObjectName(u"label4_8")
        self.label4_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_8.sizePolicy().hasHeightForWidth())
        self.label4_8.setSizePolicy(sizePolicy1)
        self.label4_8.setScaledContents(True)
        self.label4_4 = QLabel(self.frame_4)
        self.label4_4.setObjectName(u"label4_4")
        self.label4_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_4.sizePolicy().hasHeightForWidth())
        self.label4_4.setSizePolicy(sizePolicy1)
        self.label4_4.setScaledContents(True)
        self.label4_1 = QLabel(self.frame_4)
        self.label4_1.setObjectName(u"label4_1")
        self.label4_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_1.sizePolicy().hasHeightForWidth())
        self.label4_1.setSizePolicy(sizePolicy1)
        self.label4_1.setScaledContents(True)
        self.label4_7 = QLabel(self.frame_4)
        self.label4_7.setObjectName(u"label4_7")
        self.label4_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_7.sizePolicy().hasHeightForWidth())
        self.label4_7.setSizePolicy(sizePolicy1)
        self.label4_7.setScaledContents(True)
        self.label4_3 = QLabel(self.frame_4)
        self.label4_3.setObjectName(u"label4_3")
        self.label4_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_3.sizePolicy().hasHeightForWidth())
        self.label4_3.setSizePolicy(sizePolicy1)
        self.label4_3.setScaledContents(True)
        self.big_label4 = QLabel(self.frame_4)
        self.big_label4.setObjectName(u"big_label4")
        self.big_label4.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label4.sizePolicy().hasHeightForWidth())
        self.big_label4.setSizePolicy(sizePolicy)
        self.big_label4.setScaledContents(True)
        self.label4_9 = QLabel(self.frame_4)
        self.label4_9.setObjectName(u"label4_9")
        self.label4_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_9.sizePolicy().hasHeightForWidth())
        self.label4_9.setSizePolicy(sizePolicy1)
        self.label4_9.setScaledContents(True)
        self.label4_6 = QLabel(self.frame_4)
        self.label4_6.setObjectName(u"label4_6")
        self.label4_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_6.sizePolicy().hasHeightForWidth())
        self.label4_6.setSizePolicy(sizePolicy1)
        self.label4_6.setScaledContents(True)
        self.label4_5 = QLabel(self.frame_4)
        self.label4_5.setObjectName(u"label4_5")
        self.label4_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_5.sizePolicy().hasHeightForWidth())
        self.label4_5.setSizePolicy(sizePolicy1)
        self.label4_5.setScaledContents(True)
        self.label4_2 = QLabel(self.frame_4)
        self.label4_2.setObjectName(u"label4_2")
        self.label4_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label4_2.sizePolicy().hasHeightForWidth())
        self.label4_2.setSizePolicy(sizePolicy1)
        self.label4_2.setScaledContents(True)
        self.button4 = QPushButton(self.frame_4)
        self.button4.setObjectName(u"button4")
        self.button4.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        self.button4.setFlat(True)
        self.frame_2 = QFrame(self.gameFrame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(200, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.label2_8 = QLabel(self.frame_2)
        self.label2_8.setObjectName(u"label2_8")
        self.label2_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_8.sizePolicy().hasHeightForWidth())
        self.label2_8.setSizePolicy(sizePolicy1)
        self.label2_8.setScaledContents(True)
        self.label2_4 = QLabel(self.frame_2)
        self.label2_4.setObjectName(u"label2_4")
        self.label2_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_4.sizePolicy().hasHeightForWidth())
        self.label2_4.setSizePolicy(sizePolicy1)
        self.label2_4.setScaledContents(True)
        self.label2_1 = QLabel(self.frame_2)
        self.label2_1.setObjectName(u"label2_1")
        self.label2_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_1.sizePolicy().hasHeightForWidth())
        self.label2_1.setSizePolicy(sizePolicy1)
        self.label2_1.setScaledContents(True)
        self.label2_7 = QLabel(self.frame_2)
        self.label2_7.setObjectName(u"label2_7")
        self.label2_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_7.sizePolicy().hasHeightForWidth())
        self.label2_7.setSizePolicy(sizePolicy1)
        self.label2_7.setScaledContents(True)
        self.label2_3 = QLabel(self.frame_2)
        self.label2_3.setObjectName(u"label2_3")
        self.label2_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_3.sizePolicy().hasHeightForWidth())
        self.label2_3.setSizePolicy(sizePolicy1)
        self.label2_3.setScaledContents(True)
        self.big_label2 = QLabel(self.frame_2)
        self.big_label2.setObjectName(u"big_label2")
        self.big_label2.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label2.sizePolicy().hasHeightForWidth())
        self.big_label2.setSizePolicy(sizePolicy)
        self.big_label2.setScaledContents(True)
        self.label2_9 = QLabel(self.frame_2)
        self.label2_9.setObjectName(u"label2_9")
        self.label2_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_9.sizePolicy().hasHeightForWidth())
        self.label2_9.setSizePolicy(sizePolicy1)
        self.label2_9.setScaledContents(True)
        self.label2_6 = QLabel(self.frame_2)
        self.label2_6.setObjectName(u"label2_6")
        self.label2_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_6.sizePolicy().hasHeightForWidth())
        self.label2_6.setSizePolicy(sizePolicy1)
        self.label2_6.setScaledContents(True)
        self.label2_5 = QLabel(self.frame_2)
        self.label2_5.setObjectName(u"label2_5")
        self.label2_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_5.sizePolicy().hasHeightForWidth())
        self.label2_5.setSizePolicy(sizePolicy1)
        self.label2_5.setScaledContents(True)
        self.label2_2 = QLabel(self.frame_2)
        self.label2_2.setObjectName(u"label2_2")
        self.label2_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label2_2.sizePolicy().hasHeightForWidth())
        self.label2_2.setSizePolicy(sizePolicy1)
        self.label2_2.setScaledContents(True)
        self.button2 = QPushButton(self.frame_2)
        self.button2.setObjectName(u"button2")
        self.button2.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        self.button2.setFlat(True)
        self.vLine_1 = QFrame(self.gameFrame)
        self.vLine_1.setObjectName(u"vLine_1")
        self.vLine_1.setGeometry(QRect(198, 0, 2, 604))
        sizePolicy.setHeightForWidth(self.vLine_1.sizePolicy().hasHeightForWidth())
        self.vLine_1.setSizePolicy(sizePolicy)
        self.vLine_1.setFrameShadow(QFrame.Plain)
        self.vLine_1.setLineWidth(2)
        self.vLine_1.setFrameShape(QFrame.VLine)
        self.frame_3 = QFrame(self.gameFrame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(402, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.label3_8 = QLabel(self.frame_3)
        self.label3_8.setObjectName(u"label3_8")
        self.label3_8.setGeometry(QRect(70, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_8.sizePolicy().hasHeightForWidth())
        self.label3_8.setSizePolicy(sizePolicy1)
        self.label3_8.setScaledContents(True)
        self.label3_4 = QLabel(self.frame_3)
        self.label3_4.setObjectName(u"label3_4")
        self.label3_4.setGeometry(QRect(4, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_4.sizePolicy().hasHeightForWidth())
        self.label3_4.setSizePolicy(sizePolicy1)
        self.label3_4.setScaledContents(True)
        self.label3_1 = QLabel(self.frame_3)
        self.label3_1.setObjectName(u"label3_1")
        self.label3_1.setGeometry(QRect(4, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_1.sizePolicy().hasHeightForWidth())
        self.label3_1.setSizePolicy(sizePolicy1)
        self.label3_1.setScaledContents(True)
        self.label3_7 = QLabel(self.frame_3)
        self.label3_7.setObjectName(u"label3_7")
        self.label3_7.setGeometry(QRect(4, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_7.sizePolicy().hasHeightForWidth())
        self.label3_7.setSizePolicy(sizePolicy1)
        self.label3_7.setScaledContents(True)
        self.label3_3 = QLabel(self.frame_3)
        self.label3_3.setObjectName(u"label3_3")
        self.label3_3.setGeometry(QRect(136, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_3.sizePolicy().hasHeightForWidth())
        self.label3_3.setSizePolicy(sizePolicy1)
        self.label3_3.setScaledContents(True)
        self.big_label3 = QLabel(self.frame_3)
        self.big_label3.setObjectName(u"big_label3")
        self.big_label3.setGeometry(QRect(11, 15, 180, 180))
        sizePolicy.setHeightForWidth(self.big_label3.sizePolicy().hasHeightForWidth())
        self.big_label3.setSizePolicy(sizePolicy)
        self.big_label3.setScaledContents(True)
        self.label3_9 = QLabel(self.frame_3)
        self.label3_9.setObjectName(u"label3_9")
        self.label3_9.setGeometry(QRect(136, 140, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_9.sizePolicy().hasHeightForWidth())
        self.label3_9.setSizePolicy(sizePolicy1)
        self.label3_9.setScaledContents(True)
        self.label3_6 = QLabel(self.frame_3)
        self.label3_6.setObjectName(u"label3_6")
        self.label3_6.setGeometry(QRect(136, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_6.sizePolicy().hasHeightForWidth())
        self.label3_6.setSizePolicy(sizePolicy1)
        self.label3_6.setScaledContents(True)
        self.label3_5 = QLabel(self.frame_3)
        self.label3_5.setObjectName(u"label3_5")
        self.label3_5.setGeometry(QRect(70, 74, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_5.sizePolicy().hasHeightForWidth())
        self.label3_5.setSizePolicy(sizePolicy1)
        self.label3_5.setScaledContents(True)
        self.label3_2 = QLabel(self.frame_3)
        self.label3_2.setObjectName(u"label3_2")
        self.label3_2.setGeometry(QRect(70, 8, 60, 60))
        sizePolicy1.setHeightForWidth(self.label3_2.sizePolicy().hasHeightForWidth())
        self.label3_2.setSizePolicy(sizePolicy1)
        self.label3_2.setScaledContents(True)
        self.button3 = QPushButton(self.frame_3)
        self.button3.setObjectName(u"button3")
        self.button3.setGeometry(QRect(0, 0, 200, 200))
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        self.button3.setFlat(True)
        self.matchOutcomeLabel = QLabel(self.centralwidget)
        self.matchOutcomeLabel.setObjectName(u"matchOutcomeLabel")
        self.matchOutcomeLabel.setGeometry(QRect(190, 800, 551, 51))
        font = QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.matchOutcomeLabel.setFont(font)
        self.matchOutcomeLabel.setAlignment(Qt.AlignCenter)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 520, 95, 97))
        self.player2ScoreBox = QVBoxLayout(self.layoutWidget)
        self.player2ScoreBox.setObjectName(u"player2ScoreBox")
        self.player2ScoreBox.setContentsMargins(0, 0, 0, 0)
        self.player2ScoreLabel = QLabel(self.layoutWidget)
        self.player2ScoreLabel.setObjectName(u"player2ScoreLabel")
        font1 = QFont()
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setWeight(75)
        self.player2ScoreLabel.setFont(font1)

        self.player2ScoreBox.addWidget(self.player2ScoreLabel)

        self.player2Score = QLabel(self.layoutWidget)
        self.player2Score.setObjectName(u"player2Score")
        font2 = QFont()
        font2.setPointSize(40)
        font2.setBold(True)
        font2.setWeight(75)
        self.player2Score.setFont(font2)
        self.player2Score.setAlignment(Qt.AlignCenter)

        self.player2ScoreBox.addWidget(self.player2Score)

        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(90, 20, 735, 150))
        self.topLayout = QVBoxLayout(self.layoutWidget1)
        self.topLayout.setObjectName(u"topLayout")
        self.topLayout.setContentsMargins(0, 0, 0, 0)
        self.titleLabel = QLabel(self.layoutWidget1)
        self.titleLabel.setObjectName(u"titleLabel")
        font3 = QFont()
        font3.setPointSize(22)
        font3.setBold(True)
        font3.setWeight(75)
        self.titleLabel.setFont(font3)
        self.titleLabel.setFrameShape(QFrame.NoFrame)
        self.titleLabel.setTextFormat(Qt.AutoText)
        self.titleLabel.setAlignment(Qt.AlignCenter)

        self.topLayout.addWidget(self.titleLabel)

        self.belowTitleLayout = QHBoxLayout()
        self.belowTitleLayout.setObjectName(u"belowTitleLayout")
        self.startButton = QPushButton(self.layoutWidget1)
        self.startButton.setObjectName(u"startButton")

        self.belowTitleLayout.addWidget(self.startButton)

        self.roundsLabel = QLabel(self.layoutWidget1)
        self.roundsLabel.setObjectName(u"roundsLabel")
        self.roundsLabel.setFrameShape(QFrame.NoFrame)
        self.roundsLabel.setMidLineWidth(0)
        self.roundsLabel.setAlignment(Qt.AlignCenter)

        self.belowTitleLayout.addWidget(self.roundsLabel)

        self.roundsSpinBox = QSpinBox(self.layoutWidget1)
        self.roundsSpinBox.setObjectName(u"roundsSpinBox")

        self.belowTitleLayout.addWidget(self.roundsSpinBox)

        self.player1ModeLayout = QVBoxLayout()
        self.player1ModeLayout.setObjectName(u"player1ModeLayout")
        self.player1Label = QLabel(self.layoutWidget1)
        self.player1Label.setObjectName(u"player1Label")

        self.player1ModeLayout.addWidget(self.player1Label)

        self.player1Human = QCheckBox(self.layoutWidget1)
        self.player1Human.setObjectName(u"player1Human")

        self.player1ModeLayout.addWidget(self.player1Human)

        self.player1Easy = QCheckBox(self.layoutWidget1)
        self.player1Easy.setObjectName(u"player1Easy")

        self.player1ModeLayout.addWidget(self.player1Easy)

        self.player1Hard = QCheckBox(self.layoutWidget1)
        self.player1Hard.setObjectName(u"player1Hard")

        self.player1ModeLayout.addWidget(self.player1Hard)


        self.belowTitleLayout.addLayout(self.player1ModeLayout)

        self.player2ModeLayout = QVBoxLayout()
        self.player2ModeLayout.setObjectName(u"player2ModeLayout")
        self.player2Label = QLabel(self.layoutWidget1)
        self.player2Label.setObjectName(u"player2Label")

        self.player2ModeLayout.addWidget(self.player2Label)

        self.player2Human = QCheckBox(self.layoutWidget1)
        self.player2Human.setObjectName(u"player2Human")

        self.player2ModeLayout.addWidget(self.player2Human)

        self.player2Easy = QCheckBox(self.layoutWidget1)
        self.player2Easy.setObjectName(u"player2Easy")

        self.player2ModeLayout.addWidget(self.player2Easy)

        self.player2Hard = QCheckBox(self.layoutWidget1)
        self.player2Hard.setObjectName(u"player2Hard")

        self.player2ModeLayout.addWidget(self.player2Hard)


        self.belowTitleLayout.addLayout(self.player2ModeLayout)

        self.rulesButton = QPushButton(self.layoutWidget1)
        self.rulesButton.setObjectName(u"rulesButton")
        font4 = QFont()
        font4.setPointSize(11)
        self.rulesButton.setFont(font4)

        self.belowTitleLayout.addWidget(self.rulesButton)


        self.topLayout.addLayout(self.belowTitleLayout)

        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 380, 95, 97))
        self.player1ScoreBox = QVBoxLayout(self.layoutWidget2)
        self.player1ScoreBox.setObjectName(u"player1ScoreBox")
        self.player1ScoreBox.setContentsMargins(0, 0, 0, 0)
        self.player1ScoreLabel = QLabel(self.layoutWidget2)
        self.player1ScoreLabel.setObjectName(u"player1ScoreLabel")
        self.player1ScoreLabel.setFont(font1)

        self.player1ScoreBox.addWidget(self.player1ScoreLabel)

        self.player1Score = QLabel(self.layoutWidget2)
        self.player1Score.setObjectName(u"player1Score")
        self.player1Score.setFont(font2)
        self.player1Score.setAlignment(Qt.AlignCenter)

        self.player1ScoreBox.addWidget(self.player1Score)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 917, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNumber_of_rounds.setText(QCoreApplication.translate("MainWindow", u"Number of rounds", None))
        self.label9_8.setText("")
        self.label9_4.setText("")
        self.label9_1.setText("")
        self.label9_7.setText("")
        self.label9_3.setText("")
        self.big_label9.setText("")
        self.label9_9.setText("")
        self.label9_6.setText("")
        self.label9_5.setText("")
        self.label9_2.setText("")
        self.button9.setText("")
        self.label7_8.setText("")
        self.label7_4.setText("")
        self.label7_1.setText("")
        self.label7_7.setText("")
        self.label7_3.setText("")
        self.big_label7.setText("")
        self.label7_9.setText("")
        self.label7_6.setText("")
        self.label7_5.setText("")
        self.label7_2.setText("")
        self.button7.setText("")
        self.label5_8.setText("")
        self.label5_4.setText("")
        self.label5_1.setText("")
        self.label5_7.setText("")
        self.label5_3.setText("")
        self.big_label5.setText("")
        self.label5_9.setText("")
        self.label5_6.setText("")
        self.label5_5.setText("")
        self.label5_2.setText("")
        self.button5.setText("")
        self.label6_8.setText("")
        self.label6_4.setText("")
        self.label6_1.setText("")
        self.label6_7.setText("")
        self.label6_3.setText("")
        self.big_label6.setText("")
        self.label6_9.setText("")
        self.label6_6.setText("")
        self.label6_5.setText("")
        self.label6_2.setText("")
        self.button6.setText("")
        self.label8_8.setText("")
        self.label8_4.setText("")
        self.label8_1.setText("")
        self.label8_7.setText("")
        self.label8_3.setText("")
        self.big_label8.setText("")
        self.label8_9.setText("")
        self.label8_6.setText("")
        self.label8_5.setText("")
        self.label8_2.setText("")
        self.button8.setText("")
        self.label1_8.setText("")
        self.label1_4.setText("")
        self.label1_1.setText("")
        self.label1_7.setText("")
        self.label1_3.setText("")
        self.big_label1.setText("")
        self.label1_9.setText("")
        self.label1_6.setText("")
        self.label1_5.setText("")
        self.label1_2.setText("")
        self.button1.setText("")
        self.label4_8.setText("")
        self.label4_4.setText("")
        self.label4_1.setText("")
        self.label4_7.setText("")
        self.label4_3.setText("")
        self.big_label4.setText("")
        self.label4_9.setText("")
        self.label4_6.setText("")
        self.label4_5.setText("")
        self.label4_2.setText("")
        self.button4.setText("")
        self.label2_8.setText("")
        self.label2_4.setText("")
        self.label2_1.setText("")
        self.label2_7.setText("")
        self.label2_3.setText("")
        self.big_label2.setText("")
        self.label2_9.setText("")
        self.label2_6.setText("")
        self.label2_5.setText("")
        self.label2_2.setText("")
        self.button2.setText("")
        self.label3_8.setText("")
        self.label3_4.setText("")
        self.label3_1.setText("")
        self.label3_7.setText("")
        self.label3_3.setText("")
        self.big_label3.setText("")
        self.label3_9.setText("")
        self.label3_6.setText("")
        self.label3_5.setText("")
        self.label3_2.setText("")
        self.button3.setText("")
        self.matchOutcomeLabel.setText("")
        self.player2ScoreLabel.setText(QCoreApplication.translate("MainWindow", u"Player 2", None))
        self.player2Score.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"Quantum tic-tac-toe", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.roundsLabel.setText(QCoreApplication.translate("MainWindow", u" Rounds", None))
        self.player1Label.setText(QCoreApplication.translate("MainWindow", u"Player 1", None))
        self.player1Human.setText(QCoreApplication.translate("MainWindow", u"Human", None))
        self.player1Easy.setText(QCoreApplication.translate("MainWindow", u"Easy", None))
        self.player1Hard.setText(QCoreApplication.translate("MainWindow", u"Hard", None))
        self.player2Label.setText(QCoreApplication.translate("MainWindow", u"Player 2", None))
        self.player2Human.setText(QCoreApplication.translate("MainWindow", u"Human", None))
        self.player2Easy.setText(QCoreApplication.translate("MainWindow", u"Easy", None))
        self.player2Hard.setText(QCoreApplication.translate("MainWindow", u"Hard", None))
        self.rulesButton.setText(QCoreApplication.translate("MainWindow", u"Rules", None))
        self.player1ScoreLabel.setText(QCoreApplication.translate("MainWindow", u"Player 1", None))
        self.player1Score.setText(QCoreApplication.translate("MainWindow", u"0", None))
    # retranslateUi

Error: ui_quantum_tic_tac_toe.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget1'.
ui_quantum_tic_tac_toe.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget2'.

while executing '/home/michal/.local/lib/python3.8/site-packages/PySide2/uic -g python ui_quantum_tic_tac_toe.ui'
